# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-10 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pressure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodpressure',
            name='diastolic_value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bloodpressure',
            name='pulse',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bloodpressure',
            name='systolic_value',
            field=models.IntegerField(),
        ),
    ]
